package dk.jamesbabz.madkursus.outbound.mealplan;
import java.util.*; import dk.jamesbabz.madkursus.outbound.mealplan.details.*; import dk.jamesbabz.madkursus.outbound.recipe.details.RecipeEntity; import dk.jamesbabz.madkursus.service.exceptions.ResourceNotFoundException; import dk.jamesbabz.madkursus.service.models.*; import dk.jamesbabz.madkursus.service.ports.*; import jakarta.persistence.EntityManager; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Component; import org.springframework.transaction.annotation.Transactional;
@Component @RequiredArgsConstructor public class MealPlanAdapterImpl implements MealPlanPort { private final MealPlanJpaRepository repository; private final EntityManager entityManager; private final RecipePort recipePort;
 @Transactional public MealPlan save(MealPlan model){boolean creating=model.id()==null;MealPlanEntity entity;if(creating){entity=new MealPlanEntity(null,model.userId(),model.name(),model.createdAt(),model.updatedAt());for(PlannedRecipe r:model.recipes())entity.addRecipe(new PlannedRecipeEntity(null,recipeRef(r),r.recipeName(),r.portions(),r.sortOrder(),r.status()));entity=repository.saveAndFlush(entity);}else{entity=repository.findByIdAndUserId(model.id(),model.userId()).orElseThrow(()->new ResourceNotFoundException("Meal plan",model.id()));entity.update(model.name(),model.updatedAt());Set<UUID>wanted=model.recipes().stream().map(PlannedRecipe::id).filter(Objects::nonNull).collect(java.util.stream.Collectors.toSet());entity.getRecipes().removeIf(existing->!wanted.contains(existing.getId()));Map<UUID,PlannedRecipeEntity> existing=new HashMap<>();int temporary=1_000_000;for(PlannedRecipeEntity child:entity.getRecipes()){existing.put(child.getId(),child);child.update(child.getRecipe(),child.getRecipeName(),child.getPortions(),temporary++,child.getStatus());}repository.flush();for(PlannedRecipe r:model.recipes()){PlannedRecipeEntity child=r.id()==null?null:existing.get(r.id());if(child==null)entity.addRecipe(new PlannedRecipeEntity(null,recipeRef(r),r.recipeName(),r.portions(),r.sortOrder(),r.status()));else child.update(recipeRef(r),r.recipeName(),r.portions(),r.sortOrder(),r.status());}repository.flush();}return map(entity);}
 @Transactional(readOnly=true) public Optional<MealPlan> findByIdAndUserId(UUID id,UUID userId){return repository.findByIdAndUserId(id,userId).map(this::map);} @Transactional(readOnly=true) public List<MealPlan> findAllByUserId(UUID userId){Map<UUID,Recipe> recipes=recipePort.findAllByUserId(userId).stream().collect(java.util.stream.Collectors.toMap(Recipe::id,r->r));return repository.findAllByUserIdOrderByUpdatedAtDesc(userId).stream().map(e->map(e,recipes)).toList();} @Transactional(readOnly=true) public boolean existsPlannedByRecipeIdAndUserId(UUID recipeId,UUID userId){return repository.existsPlanned(recipeId,userId);}@Transactional public void detachHistoricalRecipeReferences(UUID recipeId,UUID userId){repository.detachHistorical(recipeId,userId,EnumSet.of(PlannedRecipeStatus.COOKED,PlannedRecipeStatus.SKIPPED));}@Transactional public void deleteByIdAndUserId(UUID id,UUID userId){repository.deleteByIdAndUserId(id,userId);}
 private MealPlan map(MealPlanEntity e){return new MealPlan(e.getId(),e.getUserId(),e.getName(),e.getCreatedAt(),e.getUpdatedAt(),e.getRecipes().stream().map(r->{Recipe recipe=r.getRecipe()==null?null:recipePort.findByIdAndUserId(r.getRecipe().getId(),e.getUserId()).orElseThrow(()->new ResourceNotFoundException("Recipe",r.getRecipe().getId()));return new PlannedRecipe(r.getId(),recipe,r.getRecipeName(),r.getPortions(),r.getSortOrder(),r.getStatus());}).toList());}
 private MealPlan map(MealPlanEntity e,Map<UUID,Recipe> recipes){return new MealPlan(e.getId(),e.getUserId(),e.getName(),e.getCreatedAt(),e.getUpdatedAt(),e.getRecipes().stream().map(r->new PlannedRecipe(r.getId(),r.getRecipe()==null?null:Optional.ofNullable(recipes.get(r.getRecipe().getId())).orElseThrow(()->new ResourceNotFoundException("Recipe",r.getRecipe().getId())),r.getRecipeName(),r.getPortions(),r.getSortOrder(),r.getStatus())).toList());}
 private RecipeEntity recipeRef(PlannedRecipe r){return r.recipe()==null?null:entityManager.getReference(RecipeEntity.class,r.recipe().id());}
}
