package dk.jamesbabz.madkursus.service.models;

public enum ProductCategory {
    BAKING, BREAD, DAIRY, EGG, FISH, FROZEN, FRUIT, GRAIN_PASTA, HERB, LEGUME, MEAT,
    NUT_SEED, OIL_FAT, OTHER, PRESERVED, SAUCE_CONDIMENT, SPICE, STOCK, SWEETENER,
    VEGETABLE, VINEGAR_ACID, DRY_GOODS
}
