package db.migration;
import java.nio.charset.StandardCharsets;import java.sql.*;import java.util.*;import com.fasterxml.jackson.databind.*;import org.flywaydb.core.api.migration.*;
public class V25__polish_curated_meatballs_recipe extends BaseJavaMigration{
 @Override public void migrate(Context context)throws Exception{UUID recipe=find(context,"SELECT id FROM recipe_templates WHERE normalized_name=?","kødboller i tomatsovs med pasta");UUID mix=find(context,"SELECT id FROM cooking_processes WHERE process_key=?","MIX_MEATBALL_MIXTURE");
  try(PreparedStatement shift=context.getConnection().prepareStatement("UPDATE cooking_process_parameters SET sort_order=sort_order+100 WHERE cooking_process_id=?")){shift.setObject(1,mix);shift.executeUpdate();}
  try(PreparedStatement insert=context.getConnection().prepareStatement("INSERT INTO cooking_process_parameters(id,cooking_process_id,parameter_key,label,parameter_type,required,sort_order) SELECT ?,?,'INGREDIENTS','Bundne ingredienser','INGREDIENT_LIST',false,1 WHERE NOT EXISTS(SELECT 1 FROM cooking_process_parameters WHERE cooking_process_id=? AND parameter_key='INGREDIENTS')")){insert.setObject(1,id("cooking-process-parameter:MIX_MEATBALL_MIXTURE:INGREDIENTS"));insert.setObject(2,mix);insert.setObject(3,mix);insert.executeUpdate();}
  List<String> keys=List.of("INGREDIENTS","MEAT","EGG","ONION","BINDER","LIQUID","SALT","PEPPER","OTHER_SEASONING","MIX_TIME");try(PreparedStatement order=context.getConnection().prepareStatement("UPDATE cooking_process_parameters SET sort_order=? WHERE cooking_process_id=? AND parameter_key=?")){int i=1;for(String key:keys){order.setInt(1,i++);order.setObject(2,mix);order.setString(3,key);order.addBatch();}order.executeBatch();}
  try(PreparedStatement update=context.getConnection().prepareStatement("UPDATE cooking_process_steps SET instruction_template='Kom {INGREDIENTS} i en skål.' WHERE cooking_process_id=? AND sort_order=1")){update.setObject(1,mix);update.executeUpdate();}
  JsonNode source=read().path("recipe");try(PreparedStatement insert=context.getConnection().prepareStatement("INSERT INTO recipe_template_preparation_steps(id,recipe_template_id,instruction,sort_order) VALUES (?,?,?,?)")){int i=1;for(JsonNode text:source.path("preparation")){insert.setObject(1,id("recipe-template-preparation:"+recipe+":"+i));insert.setObject(2,recipe);insert.setString(3,text.asText());insert.setInt(4,i++);insert.addBatch();}insert.executeBatch();}
  try(PreparedStatement insert=context.getConnection().prepareStatement("INSERT INTO recipe_template_equipment_requirements(id,recipe_template_id,equipment_type,label,sort_order) VALUES (?,?,?,?,?)")){int i=1;for(JsonNode value:source.path("equipment")){insert.setObject(1,id("recipe-template-equipment:"+recipe+":"+i));insert.setObject(2,recipe);insert.setString(3,value.path("equipmentType").asText(null));insert.setString(4,value.path("label").asText(null));insert.setInt(5,i++);insert.addBatch();}insert.executeBatch();}
  updateIngredient(context,recipe,"Hakket oksekød",null,null);updateIngredient(context,recipe,"Hakkede tomater",null,null);updateIngredient(context,recipe,"Sødmælk","Letmælk",null);
  try(PreparedStatement delete=context.getConnection().prepareStatement("DELETE FROM recipe_template_steps WHERE recipe_template_id=? AND (instruction LIKE 'Lav hele mise en place først.%' OR instruction LIKE 'Kom 1 liter vand pr. portion%')")){delete.setObject(1,recipe);delete.executeUpdate();}
  updateStep(context,recipe,"Tilsæt hvidløg, og steg i 30 sekunder.%","Tilsæt hvidløget og steg i 30 sekunder under omrøring. Tilsæt tomatpuré og steg videre i 1 minut under omrøring.");
  updateStep(context,recipe,"Tilsæt hakkede tomater, ½ dl vand pr. portion%","Tilsæt hakkede tomater, 1 dl vand, timian, ½ tsk salt og 5 omgange peber. Skrab den brunede stegerest fra panden ind i sovsen.");
 }
 private void updateIngredient(Context c,UUID recipe,String oldName,String newName,String preparation)throws Exception{String sql="UPDATE recipe_template_ingredients i SET preparation=?"+(newName==null?"":" ,product_template_id=(SELECT id FROM product_templates WHERE normalized_name=?)")+" WHERE i.recipe_template_id=? AND i.product_template_id=(SELECT id FROM product_templates WHERE normalized_name=?)";try(PreparedStatement s=c.getConnection().prepareStatement(sql)){int x=1;s.setString(x++,preparation);if(newName!=null)s.setString(x++,newName.toLowerCase(Locale.ROOT));s.setObject(x++,recipe);s.setString(x,oldName.toLowerCase(Locale.ROOT));s.executeUpdate();}}
 private void updateStep(Context c,UUID recipe,String pattern,String text)throws Exception{try(PreparedStatement s=c.getConnection().prepareStatement("UPDATE recipe_template_steps SET instruction=? WHERE recipe_template_id=? AND instruction LIKE ?")){s.setString(1,text);s.setObject(2,recipe);s.setString(3,pattern);s.executeUpdate();}}
 private UUID find(Context c,String sql,String value)throws Exception{try(PreparedStatement s=c.getConnection().prepareStatement(sql)){s.setString(1,value);try(ResultSet r=s.executeQuery()){if(r.next())return r.getObject(1,UUID.class);}}throw new IllegalStateException("Missing seed reference "+value);}
 private JsonNode read()throws Exception{try(var in=getClass().getResourceAsStream("/db/migration/data/V23__curated_meatballs.json")){return new ObjectMapper().readTree(in);}}
 private UUID id(String value){return UUID.nameUUIDFromBytes(value.getBytes(StandardCharsets.UTF_8));}
}
