package dk.jamesbabz.madkursus.service.applications;

import com.fasterxml.jackson.databind.ObjectMapper;
import dk.jamesbabz.madkursus.outbound.dtunutrition.*;
import dk.jamesbabz.madkursus.service.models.*;
import dk.jamesbabz.madkursus.service.ports.ProductTemplatePort;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

class DtuNutritionAdminServiceTest {
    DtuReferenceFoodRepository foods=mock(DtuReferenceFoodRepository.class);
    ProductTemplateDtuMappingRepository mappings=mock(ProductTemplateDtuMappingRepository.class);
    ProductTemplatePort templates=mock(ProductTemplatePort.class);
    DtuNutritionAdminService service=new DtuNutritionAdminService(foods,mappings,templates,new ObjectMapper().findAndRegisterModules());
    @BeforeEach void defaults(){lenient().when(foods.versions()).thenReturn(List.of("5.5"));lenient().when(mappings.findAll()).thenReturn(List.of());lenient().when(mappings.save(any())).thenAnswer(call->call.getArgument(0));}

    @Test void importsVersionedReferenceDatasetOnlyOnce(){when(foods.versions()).thenReturn(List.of());var result=service.importDataset(new DtuNutritionAdminService.Dataset("test",LocalDate.of(2026,1,1),"https://example.test",List.of(new DtuNutritionAdminService.DatasetFood("716","Løg, rå",bd("7.3"),"rå"))));assertThat(result.importedFoods()).isOne();verify(foods).saveAll(any());}
    @Test void importsOfficialBundledReferenceDataset(){when(foods.versions()).thenReturn(List.of());var result=service.importBundled();assertThat(result.datasetVersion()).isEqualTo("5.5");assertThat(result.importedFoods()).isEqualTo(1381);verify(foods).saveAll(any());}
    @Test void createsExactAndAliasSuggestions(){var onion=food("716","Løg",bd("7.3"));when(foods.search("5.5","")).thenReturn(List.of(onion));assertThat(service.suggest(template("Løg",List.of())).classification()).isEqualTo(DtuNutritionAdminService.MatchClassification.EXACT);assertThat(service.suggest(template("Onion",List.of("Løg"))).classification()).isEqualTo(DtuNutritionAdminService.MatchClassification.HIGH_CONFIDENCE);}
    @Test void basicRawFoodIsStrongAndPreparedConflictRanksLower(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Løg, rå",bd("7")),food("2","Løg, kogt",bd("6"))));assertThat(service.suggest(template("Løg",List.of())).classification()).isEqualTo(DtuNutritionAdminService.MatchClassification.HIGH_CONFIDENCE);assertThat(service.suggest(template("Kogt løg",List.of())).candidates().getFirst().food().foodId()).isEqualTo("2");verify(mappings,never()).save(any());verify(templates,never()).updateNutrition(any(),any());}
    @Test void safeInflectionAndExplicitStateImproveRanking(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Tigerreje, opdræt, rå, dybfrost",bd("1")),food("2","Blåbær, rå",bd("10")),food("3","Blåbær, dybfrost",bd("9"))));assertThat(service.suggest(template("Tigerrejer",List.of())).classification()).isNotEqualTo(DtuNutritionAdminService.MatchClassification.NO_MATCH);assertThat(service.suggest(template("Frosne blåbær",List.of())).candidates().getFirst().food().foodId()).isEqualTo("3");}
    @Test void localCatalogSearchWorksWithoutNetwork(){var reference=food("716","Løg, rå",bd("7.3"));when(foods.search("5.5","")).thenReturn(List.of(reference));assertThat(service.search("Løg")).extracting(DtuNutritionAdminService.Food::foodId).containsExactly("716");}
    @Test void manualSearchUsesOrderIndependentSignificantTokensAndKeepsSubstringAndId(){var ground=food("942","Oksekød, hakket, 10-15% fedt, rå",bd("0"));var bouillon=food("1253","Bouillon, oksekød, koncentreret, terning",bd("2"));when(foods.search("5.5","")).thenReturn(List.of(ground,bouillon));assertThat(service.search("hakket oksekød")).extracting(DtuNutritionAdminService.Food::foodId).containsExactly("942");assertThat(service.search("oksekød hakket")).extracting(DtuNutritionAdminService.Food::foodId).containsExactly("942");assertThat(service.search("1253")).extracting(DtuNutritionAdminService.Food::foodId).containsExactly("1253");}
    @Test void explicitApprovalPersistsMappingAndCanonicalNutrition(){var product=template("Løg",List.of());var reference=food("716","Løg, rå",bd("7.3"));when(templates.findById(product.id())).thenReturn(Optional.of(product));when(foods.findByDatasetVersionAndFoodId("5.5","716")).thenReturn(Optional.of(reference));var nutrition=mock(NutritionAdminService.class);var updated=new NutritionAdminService.Entry(product,"LOEG",NutritionAdminService.Status.KNOWN,0);when(nutrition.update(eq(product.id()),any())).thenReturn(updated);service.approve(new DtuNutritionAdminService.Approval(product.id(),"5.5","716"),nutrition);ArgumentCaptor<NutritionData> data=ArgumentCaptor.forClass(NutritionData.class);verify(nutrition).update(eq(product.id()),data.capture());assertThat(data.getValue().externalFoodId()).isEqualTo("716");verify(mappings).save(any(ProductTemplateDtuMappingEntity.class));}
    @Test void refreshKeepsMappingAndFlagsChangedValueForReview(){UUID id=UUID.randomUUID();var oldFood=food("716","Løg, rå",bd("7.3"));var fresh=new DtuReferenceFoodEntity("5.6","716","Løg, rå","løg rå",bd("7.5"),"rå",LocalDate.of(2026,8,1),"https://example.test");when(foods.versions()).thenReturn(List.of("5.6","5.5"));when(mappings.findAll()).thenReturn(List.of(new ProductTemplateDtuMappingEntity(id,"5.5","716",bd("7.3"))));when(foods.findByDatasetVersionAndFoodId("5.5","716")).thenReturn(Optional.of(oldFood));when(foods.findByDatasetVersionAndFoodId("5.6","716")).thenReturn(Optional.of(fresh));var mapping=service.mapping(id);assertThat(mapping.status()).isEqualTo(DtuNutritionAdminService.MappingStatus.REQUIRES_REVIEW);assertThat(mapping.approvedCarbohydrateGrams()).isEqualByComparingTo("7.3");verify(templates,never()).updateNutrition(any(),any());}
    @Test void bulkApprovalRejectsReviewRequiredSuggestionBeforeAnyNutritionUpdate(){var product=template("Løg",List.of());when(templates.findById(product.id())).thenReturn(Optional.of(product));when(foods.search("5.5","")).thenReturn(List.of(food("1","Løg, rå",bd("7")),food("2","Løg, kogt",bd("6"))));var nutrition=mock(NutritionAdminService.class);assertThatThrownBy(()->service.approveAll(List.of(new DtuNutritionAdminService.Approval(product.id(),"5.5","1")),nutrition)).isInstanceOf(dk.jamesbabz.madkursus.service.exceptions.InvalidInputException.class);verify(nutrition,never()).update(any(),any());}

    @Test void ranksWordOrderCompoundsRawAndCannedSemantically(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Sauce, barbeque",bd("30")),food("2","And, brystkød, rå",bd("0")),food("3","Majs, konserves",bd("12"))));assertThat(service.suggest(template("Barbecuesauce",List.of())).candidates().getFirst().food().foodId()).isEqualTo("1");assertThat(service.suggest(template("Andebryst",List.of())).candidates().getFirst().food().foodId()).isEqualTo("2");assertThat(service.suggest(template("Majs på dåse",List.of("majs konserves"))).candidates().getFirst().food().foodId()).isEqualTo("3");}
    @Test void knownUnsafePatternsStayOutOfStrongQueue(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Gær, tørret",bd("30")),food("2","Sojabønner, tørrede, rå",bd("10")),food("3","Kanel, stang",bd("20"))));assertThat(service.suggest(template("Frisk gær",List.of("gær"))).classification()).isNotIn(DtuNutritionAdminService.MatchClassification.EXACT,DtuNutritionAdminService.MatchClassification.HIGH_CONFIDENCE);assertThat(service.suggest(template("Edamame",List.of("sojabønner"))).classification()).isNotIn(DtuNutritionAdminService.MatchClassification.EXACT,DtuNutritionAdminService.MatchClassification.HIGH_CONFIDENCE);assertThat(service.suggest(template("Kanel",List.of("stødt kanel"))).classification()).isNotIn(DtuNutritionAdminService.MatchClassification.EXACT,DtuNutritionAdminService.MatchClassification.HIGH_CONFIDENCE);}
    @Test void groundBeefCandidateRetrievalIsOrderIndependentAndRejectsDerivedBeef(){when(foods.search("5.5","")).thenReturn(List.of(food("942","Oksekød, hakket, 10-15% fedt, rå",bd("0")),food("1067","Oksekød, hakket, 15-20% fedt, rå",bd("0")),food("1253","Bouillon, oksekød, koncentreret, terning",bd("2")),food("287","Spegepølse, oksekød",bd("1")),food("1981","Wokret med oksekød, takeaway",bd("4"))));var first=service.suggest(template("Hakket oksekød",List.of())).candidates();var second=service.suggest(template("Oksekød hakket",List.of())).candidates();assertThat(first).extracting(candidate->candidate.food().foodId()).containsExactlyElementsOf(second.stream().map(candidate->candidate.food().foodId()).toList()).containsExactlyInAnyOrder("942","1067");}
    @Test void compoundsAndSafeWordOrderKeepTheSameEligibleIdentity(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Sauce, barbeque",bd("30")),food("2","And, brystkød, rå",bd("0"))));assertThat(service.suggest(template("Barbecuesauce",List.of())).candidates().getFirst().food().foodId()).isEqualTo("1");assertThat(service.suggest(template("Sauce barbeque",List.of())).candidates().getFirst().food().foodId()).isEqualTo("1");assertThat(service.suggest(template("Andebryst",List.of())).candidates().getFirst().food().foodId()).isEqualTo("2");assertThat(service.suggest(template("And brystkød",List.of())).candidates().getFirst().food().foodId()).isEqualTo("2");}
    @Test void tomatoIdentityExcludesFishInTomatoAndRanksCannedTomatoFirst(){when(foods.search("5.5","")).thenReturn(List.of(food("960","Makrel i tomat, konserves",bd("3")),food("924","Sardin, i tomat, konserves",bd("2")),food("751","Tun i tomat, konserves",bd("1")),food("596","Tomat, flået, konserves",bd("4")),food("451","Tomat, dansk, rå",bd("3"))));var result=service.suggest(template("Hakkede tomater",List.of("tomater på dåse"),ProductCategory.PRESERVED));assertThat(result.candidates().getFirst().food().foodId()).isEqualTo("596");assertThat(result.candidates()).extracting(candidate->candidate.food().foodId()).doesNotContain("960","924","751");}
    @Test void derivedTypesAndMaterialFormsRemainIdentityBoundaries(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Majsolie",bd("1")),food("2","Majs, kerner, konserves",bd("2")),food("3","Fløde 9 %",bd("3")),food("4","Fløde 38 %, piskefløde",bd("4"))));assertThat(service.suggest(template("Majs",List.of())).candidates()).extracting(candidate->candidate.food().foodId()).doesNotContain("1");assertThat(service.suggest(template("Piskefløde",List.of("fløde"))).candidates().getFirst().food().foodId()).isEqualTo("4");}

    @Test void fourZeroCarbohydrateGroundBeefVariantsAutoResolveDeterministically(){when(foods.search("5.5","")).thenReturn(List.of(food("1067","Oksekød, hakket, 15-20% fedt, rå",bd("0")),food("942","Oksekød, hakket, 10-15% fedt, rå",bd("0")),food("1066","Oksekød, hakket, 5-10% fedt, rå",bd("0")),food("1100","Oksekød, hakket, 8-12% fedt, rå",bd("0"))));var result=service.suggest(template("Hakket oksekød",List.of()));assertThat(result.resolution()).isEqualTo(DtuNutritionAdminService.Resolution.AUTO_EQUIVALENT_CARBOHYDRATE);assertThat(result.equivalentCandidateCount()).isEqualTo(4);assertThat(result.carbohydrateSpread()).isEqualByComparingTo("0");assertThat(result.representative().foodId()).isEqualTo("942");}
    @Test void representativeIsRealCandidateClosestToMean(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Testmad 1",bd("4.1")),food("2","Testmad 2",bd("4.6")),food("3","Testmad 3",bd("5.0"))));var result=service.suggest(template("Testmad",List.of()));assertThat(result.resolution()).isEqualTo(DtuNutritionAdminService.Resolution.AUTO_EQUIVALENT_CARBOHYDRATE);assertThat(result.representative().foodId()).isEqualTo("2");assertThat(result.candidates()).extracting(candidate->candidate.food().foodId()).contains("2");}
    @Test void spreadExactlyTwoAutoResolvesButLargerSpreadRequiresReview(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Testmad 1",bd("3")),food("2","Testmad 2",bd("5"))));assertThat(service.suggest(template("Testmad",List.of())).resolution()).isEqualTo(DtuNutritionAdminService.Resolution.AUTO_EQUIVALENT_CARBOHYDRATE);service=new DtuNutritionAdminService(foods,mappings,templates,new ObjectMapper().findAndRegisterModules());when(foods.search("5.5","")).thenReturn(List.of(food("1","Testmad 1",bd("3")),food("2","Testmad 2",bd("5.1"))));assertThat(service.suggest(template("Testmad",List.of())).resolution()).isEqualTo(DtuNutritionAdminService.Resolution.NONE);}
    @Test void similarCarbohydrateNeverCrossesSemanticOrStateBoundaries(){when(foods.search("5.5","")).thenReturn(List.of(food("596","Tomat, flået, konserves",bd("4")),food("960","Makrel i tomat, konserves",bd("4"))));assertThat(service.suggest(template("Hakkede tomater",List.of("tomater på dåse"),ProductCategory.PRESERVED)).equivalentCandidateCount()).isNotEqualTo(2);service=new DtuNutritionAdminService(foods,mappings,templates,new ObjectMapper().findAndRegisterModules());when(foods.search("5.5","")).thenReturn(List.of(food("1","Løg, rå",bd("7")),food("2","Løg, kogt",bd("7"))));assertThat(service.suggest(template("Løg",List.of())).resolution()).isEqualTo(DtuNutritionAdminService.Resolution.NONE);}
    @Test void explicitSafeApprovalPersistsRealRepresentativeAndResolutionProvenance(){var product=template("Hakket oksekød",List.of());var first=food("2","Oksekød, hakket, 15-20% fedt, rå",bd("0"));var representative=food("1","Oksekød, hakket, 10-15% fedt, rå",bd("0"));when(foods.search("5.5","")).thenReturn(List.of(first,representative));when(templates.search("",null)).thenReturn(List.of(product));when(templates.findById(product.id())).thenReturn(Optional.of(product));when(foods.findByDatasetVersionAndFoodId("5.5","1")).thenReturn(Optional.of(representative));var nutrition=mock(NutritionAdminService.class);when(nutrition.update(eq(product.id()),any())).thenReturn(new NutritionAdminService.Entry(product,"HAKKET_OKSEKOED",NutritionAdminService.Status.KNOWN_ZERO,1));assertThat(service.approveSafe(nutrition)).hasSize(1);ArgumentCaptor<NutritionData> data=ArgumentCaptor.forClass(NutritionData.class);verify(nutrition).update(eq(product.id()),data.capture());assertThat(data.getValue().externalFoodId()).isEqualTo("1");assertThat(data.getValue().note()).contains("AUTO_EQUIVALENT_CARBOHYDRATE","candidateCount=2","spread=0");verify(mappings).save(any(ProductTemplateDtuMappingEntity.class));}
    @Test void suggestingAutoResolutionNeverPersistsAndManualApprovalCanOverrideIt(){var product=template("Hakket oksekød",List.of());var first=food("1","Oksekød, hakket, 10-15% fedt, rå",bd("0"));var override=food("2","Oksekød, hakket, 15-20% fedt, rå",bd("0"));when(foods.search("5.5","")).thenReturn(List.of(first,override));assertThat(service.suggest(product).resolution()).isEqualTo(DtuNutritionAdminService.Resolution.AUTO_EQUIVALENT_CARBOHYDRATE);verify(nutritionUpdates(),never()).updateNutrition(any(),any());verify(mappings,never()).save(any());when(templates.findById(product.id())).thenReturn(Optional.of(product));when(foods.findByDatasetVersionAndFoodId("5.5","2")).thenReturn(Optional.of(override));service.approve(new DtuNutritionAdminService.Approval(product.id(),"5.5","2"),mock(NutritionAdminService.class));verify(mappings).save(argThat(mapping->mapping.getFoodId().equals("2")));}
    @Test void reviewExportBroadSearchIsOrderIndependentWithoutWeakeningAutomaticEligibility(){when(foods.search("5.5","")).thenReturn(List.of(food("1","Løg, rå",bd("7"))));var review=service.reviewCandidates(template("Tørret løg",List.of()));assertThat(review.automaticCandidates()).isEmpty();assertThat(review.broadSearchCandidates()).extracting(candidate->candidate.food().foodId()).containsExactly("1");assertThat(review.broadSearchCandidates().getFirst().reason()).contains("bestod ikke den automatiske semantiske matcher");}

    private DtuReferenceFoodEntity food(String id,String name,BigDecimal grams){String normalized=java.text.Normalizer.normalize(name.toLowerCase(),java.text.Normalizer.Form.NFKD).replaceAll("\\p{M}+","").replaceAll("[^a-z0-9æøå]+"," ").trim();return new DtuReferenceFoodEntity("5.5",id,name,normalized,grams,name.contains(",")?name.substring(name.indexOf(',')+1).trim():null,LocalDate.of(2025,11,1),"https://doi.org/10.11583/DTU.29500682");}
    private ProductTemplate template(String name,List<String> aliases){return new ProductTemplate(UUID.randomUUID(),name,ProductCategory.OTHER,Unit.GRAM,InventoryTrackingMode.QUANTITY,aliases,false,List.of(),null);}
    private ProductTemplate template(String name,List<String> aliases,ProductCategory category){return new ProductTemplate(UUID.randomUUID(),name,category,Unit.GRAM,InventoryTrackingMode.QUANTITY,aliases,false,List.of(),null);}
    private BigDecimal bd(String value){return new BigDecimal(value);}
    private ProductTemplatePort nutritionUpdates(){return templates;}
}
