package dk.jamesbabz.madkursus.service.applications;
import java.math.BigDecimal; import java.time.Instant; import java.util.*; import dk.jamesbabz.madkursus.service.exceptions.*; import dk.jamesbabz.madkursus.service.models.*; import dk.jamesbabz.madkursus.service.ports.*; import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class) class MealPlanServiceTest { @Mock MealPlanPort port;@Mock RecipeService recipes;@Mock RecipeInteractionService interactions;@Mock CurrentUserProvider currentUser;@InjectMocks MealPlanService service;UUID user=UUID.randomUUID();
 @Test void createsAtomicPlanWithWholePortionsAndPreservesRecipeQuantities(){Recipe a=recipe("A","0.5"),b=recipe("B","200");when(currentUser.currentUserId()).thenReturn(user);when(recipes.get(a.id())).thenReturn(a);when(recipes.get(b.id())).thenReturn(b);when(port.save(any())).thenAnswer(c->c.getArgument(0));MealPlan result=service.create(" Uge 33 ",List.of(new RecipeSelection(a.id(),new BigDecimal("4")),new RecipeSelection(b.id(),new BigDecimal("2"))));assertThat(result.name()).isEqualTo("Uge 33");assertThat(result.recipes()).extracting(PlannedRecipe::portions).containsExactly(4,2);assertThat(result.recipes()).extracting(PlannedRecipe::sortOrder).containsExactly(1,2);assertThat(a.ingredients().getFirst().quantity()).isEqualByComparingTo("0.5");}
 @Test void rejectsBlankNameAndFractionalPortions(){assertThatThrownBy(()->service.create(" ",List.of())).isInstanceOf(InvalidInputException.class);Recipe r=recipe("A","1");when(recipes.get(r.id())).thenReturn(r);assertThatThrownBy(()->service.create("Plan",List.of(new RecipeSelection(r.id(),new BigDecimal("1.5"))))).isInstanceOf(InvalidInputException.class);}
 @Test void requirementsIncludeOnlyPlannedRecipesAndExcludeTheCurrentPlan(){MealPlan plan=plan(PlannedRecipeStatus.PLANNED,PlannedRecipeStatus.COOKED,PlannedRecipeStatus.SKIPPED);owned(plan);when(interactions.calculate(any(),eq(plan.id()))).thenReturn(new RecipeRequirementCalculation(List.of()));service.requirements(plan.id());verify(interactions).calculate(argThat(s->s.size()==1&&s.getFirst().recipeId().equals(plan.recipes().getFirst().recipe().id())),eq(plan.id()));}
 @Test void addingPlanMissingToShoppingListAlsoExcludesTheCurrentPlan(){MealPlan plan=plan(PlannedRecipeStatus.PLANNED);owned(plan);when(interactions.addMissingToShoppingList(any(),eq(plan.id()))).thenReturn(new RecipeRequirementCalculation(List.of()));service.addMissing(plan.id());verify(interactions).addMissingToShoppingList(argThat(s->s.size()==1),eq(plan.id()));}
 @Test void cookingUsesPlannedPortionsOnceThenMarksOccurrenceCooked(){MealPlan plan=plan(PlannedRecipeStatus.PLANNED);owned(plan);when(interactions.cook(plan.recipes().getFirst().recipe().id(),BigDecimal.valueOf(2),plan.id())).thenReturn(mock(RecipeCookResult.class));when(port.save(any())).thenAnswer(c->c.getArgument(0));service.cook(plan.id(),plan.recipes().getFirst().id());verify(interactions).cook(plan.recipes().getFirst().recipe().id(),BigDecimal.valueOf(2),plan.id());verify(port).save(argThat(p->p.recipes().getFirst().status()==PlannedRecipeStatus.COOKED));MealPlan cooked=new MealPlan(plan.id(),user,plan.name(),plan.createdAt(),plan.updatedAt(),List.of(new PlannedRecipe(plan.recipes().getFirst().id(),plan.recipes().getFirst().recipe(),2,1,PlannedRecipeStatus.COOKED)));when(port.findByIdAndUserId(plan.id(),user)).thenReturn(Optional.of(cooked));assertThatThrownBy(()->service.cook(plan.id(),cooked.recipes().getFirst().id())).isInstanceOf(ConflictException.class);verifyNoMoreInteractions(interactions);}
 @Test void skipExcludesWithoutCookingAndCanReturnToPlanned(){MealPlan plan=plan(PlannedRecipeStatus.PLANNED);owned(plan);when(port.save(any())).thenAnswer(c->c.getArgument(0));MealPlan skipped=service.skip(plan.id(),plan.recipes().getFirst().id());assertThat(skipped.recipes().getFirst().status()).isEqualTo(PlannedRecipeStatus.SKIPPED);verify(interactions,never()).cook(any(),any());when(port.findByIdAndUserId(plan.id(),user)).thenReturn(Optional.of(skipped));assertThat(service.skip(plan.id(),skipped.recipes().getFirst().id()).recipes().getFirst().status()).isEqualTo(PlannedRecipeStatus.PLANNED);}
 @Test void crossUserPlanIsNotFound(){UUID id=UUID.randomUUID();when(currentUser.currentUserId()).thenReturn(user);when(port.findByIdAndUserId(id,user)).thenReturn(Optional.empty());assertThatThrownBy(()->service.get(id)).isInstanceOf(ResourceNotFoundException.class);}
 @Test void renamesAddsUpdatesRemovesAndDeletesOwnedPlan(){MealPlan plan=plan(PlannedRecipeStatus.PLANNED);Recipe added=recipe("Ny","1");owned(plan);when(port.save(any())).thenAnswer(c->c.getArgument(0));assertThat(service.rename(plan.id(),"Nyt navn").name()).isEqualTo("Nyt navn");when(recipes.get(added.id())).thenReturn(added);MealPlan withAdded=service.addRecipe(plan.id(),added.id(),4);assertThat(withAdded.recipes()).hasSize(2);assertThat(withAdded.recipes().getLast().portions()).isEqualTo(4);when(port.findByIdAndUserId(plan.id(),user)).thenReturn(Optional.of(plan));MealPlan changed=service.updateRecipe(plan.id(),plan.recipes().getFirst().id(),3,1);assertThat(changed.recipes().getFirst().portions()).isEqualTo(3);when(port.findByIdAndUserId(plan.id(),user)).thenReturn(Optional.of(changed));assertThat(service.removeRecipe(plan.id(),changed.recipes().getFirst().id()).recipes()).isEmpty();when(port.findByIdAndUserId(plan.id(),user)).thenReturn(Optional.of(plan));service.delete(plan.id());verify(port).deleteByIdAndUserId(plan.id(),user);}
 @Test void deletedSkippedRecipeRemainsHistoricalAndCannotBeReactivated(){PlannedRecipe skipped=new PlannedRecipe(UUID.randomUUID(),null,"Slettet ret",2,1,PlannedRecipeStatus.SKIPPED);MealPlan plan=new MealPlan(UUID.randomUUID(),user,"Historik",Instant.now(),Instant.now(),List.of(skipped));owned(plan);assertThatThrownBy(()->service.skip(plan.id(),skipped.id())).isInstanceOf(ConflictException.class).hasMessageContaining("slettede opskrift");verify(port,never()).save(any());}
 private void owned(MealPlan p){when(currentUser.currentUserId()).thenReturn(user);when(port.findByIdAndUserId(p.id(),user)).thenReturn(Optional.of(p));}private MealPlan plan(PlannedRecipeStatus...statuses){List<PlannedRecipe> list=new ArrayList<>();int i=1;for(var s:statuses)list.add(new PlannedRecipe(UUID.randomUUID(),recipe("R"+i,"1"),2,i++,s));return new MealPlan(UUID.randomUUID(),user,"Plan",Instant.now(),Instant.now(),list);}private Recipe recipe(String name,String q){ProductTemplate t=new ProductTemplate(UUID.randomUUID(),"Vare",ProductCategory.OTHER,Unit.PIECE,List.of(),false);return new Recipe(UUID.randomUUID(),user,name,null,Instant.now(),Instant.now(),List.of(new RecipeIngredient(UUID.randomUUID(),t,new BigDecimal(q),RecipeUnit.PIECE,null,1)),List.of());}
}
