package dk.jamesbabz.madkursus.service.applications;
import dk.jamesbabz.madkursus.service.models.*;import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.util.*;import static org.assertj.core.api.Assertions.*;
class RecipeInstructionRendererTest {
 private final RecipeInstructionRenderer renderer=new RecipeInstructionRenderer();
 @Test void ingredientPartialComponentScaledNumberAndStaticTextRenderAtOneTwoAndFourPortions(){UUID meatId=UUID.randomUUID(),eggId=UUID.randomUUID(),flourId=UUID.randomUUID(),componentId=UUID.randomUUID();List<RecipeTemplateIngredient> ingredients=List.of(ingredient(meatId,"Hakket oksekød","200",RecipeUnit.GRAM),ingredient(eggId,"Æg","0.5",RecipeUnit.PIECE),ingredient(flourId,"Hvedemel","2",RecipeUnit.TABLESPOON));PreparedComponent component=new PreparedComponent(componentId,"MIX","Ingredienser til fars",1,List.of(),List.of());RecipeStructuredInstruction instruction=new RecipeStructuredInstruction(List.of(text("Mål "),ingredient(meatId,null,null),text(", "),ingredient(eggId,null,null),text(" og "),ingredient(flourId,new BigDecimal("1"),RecipeUnit.TABLESPOON),text(". Form ca. "),number("6"),text(" kødboller; størrelsen er 2 cm og hviletiden 30 sekunder. Brug "),component(componentId),text(".")));
  assertThat(renderer.render(instruction,ingredients,List.of(component),BigDecimal.ONE)).isEqualTo("Mål 200 g Hakket oksekød, ½ stk Æg og 1 spsk Hvedemel. Form ca. 6 kødboller; størrelsen er 2 cm og hviletiden 30 sekunder. Brug Ingredienser til fars.");
  assertThat(renderer.render(instruction,ingredients,List.of(component),new BigDecimal("2"))).contains("400 g Hakket oksekød","1 stk Æg","2 spsk Hvedemel","12 kødboller","2 cm","30 sekunder");
  assertThat(renderer.render(instruction,ingredients,List.of(component),new BigDecimal("4"))).contains("800 g Hakket oksekød","2 stk Æg","4 spsk Hvedemel","24 kødboller","2 cm","30 sekunder");}
 @Test void grinderTurnsRoundToPracticalWholeTurns(){UUID id=UUID.randomUUID();var instruction=new RecipeStructuredInstruction(List.of(ingredient(id,null,null)));assertThat(renderer.render(instruction,List.of(ingredient(id,"Sort peber","7.5",RecipeUnit.GRINDER_TURN)),List.of(),BigDecimal.ONE)).isEqualTo("8 omgange Sort peber");assertThat(renderer.render(instruction,List.of(ingredient(id,"Sort peber","7.5",RecipeUnit.GRINDER_TURN)),List.of(),new BigDecimal("3"))).isEqualTo("23 omgange Sort peber");}
 @Test void untrackedWaterStillRendersAndScalesAsRecipeData(){UUID id=UUID.randomUUID();ProductTemplate water=new ProductTemplate(UUID.randomUUID(),"Vand",ProductCategory.OTHER,Unit.MILLILITER,InventoryTrackingMode.UNTRACKED,List.of(),true);var value=new RecipeTemplateIngredient(id,water,new BigDecimal("0.5"),RecipeUnit.DECILITER,null,1);var instruction=new RecipeStructuredInstruction(List.of(ingredient(id,null,null)));assertThat(renderer.render(instruction,List.of(value),List.of(),BigDecimal.ONE)).isEqualTo("½ dl Vand");assertThat(renderer.render(instruction,List.of(value),List.of(),new BigDecimal("2"))).isEqualTo("1 dl Vand");assertThat(renderer.render(instruction,List.of(value),List.of(),new BigDecimal("4"))).isEqualTo("2 dl Vand");}
 private RecipeTemplateIngredient ingredient(UUID id,String name,String quantity,RecipeUnit unit){return new RecipeTemplateIngredient(id,new ProductTemplate(UUID.randomUUID(),name,ProductCategory.OTHER,Unit.GRAM,List.of(),true),new BigDecimal(quantity),unit,null,1);}
 private RecipeInstructionPart text(String value){return new RecipeInstructionPart(value,null,null,null,null,null);}private RecipeInstructionPart ingredient(UUID id,BigDecimal q,RecipeUnit u){return new RecipeInstructionPart(null,id,q,u,null,null);}private RecipeInstructionPart component(UUID id){return new RecipeInstructionPart(null,null,null,null,id,null);}private RecipeInstructionPart number(String n){return new RecipeInstructionPart(null,null,null,null,null,new BigDecimal(n));}
}
