package dk.jamesbabz.madkursus.service.applications;
import java.math.BigDecimal; import java.time.Instant; import java.util.*; import dk.jamesbabz.madkursus.service.exceptions.*; import dk.jamesbabz.madkursus.service.models.*; import dk.jamesbabz.madkursus.service.ports.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class MealPlanService { private final MealPlanPort port; private final RecipeService recipes; private final RecipeInteractionService interactions; private final CurrentUserProvider currentUser;
 public List<MealPlan> getAll(){return port.findAllByUserId(currentUser.currentUserId());} public MealPlan get(UUID id){return port.findByIdAndUserId(id,currentUser.currentUserId()).orElseThrow(()->new ResourceNotFoundException("Meal plan",id));}
 @Transactional public MealPlan create(String name,List<RecipeSelection> selections){validateName(name);if(selections==null||selections.isEmpty())throw new InvalidInputException("Select at least one recipe");List<PlannedRecipe> planned=new ArrayList<>();int order=1;for(RecipeSelection s:selections)planned.add(new PlannedRecipe(null,recipes.get(s.recipeId()),wholePortions(s.portions()),order++,PlannedRecipeStatus.PLANNED));Instant now=Instant.now();UUID user=currentUser.currentUserId();return port.save(new MealPlan(null,user,name.trim(),now,now,List.copyOf(planned)));}
 @Transactional public MealPlan rename(UUID id,String name){validateName(name);MealPlan old=get(id);return save(old,name,old.recipes());}
 @Transactional public MealPlan addRecipe(UUID id,UUID recipeId,int portions){MealPlan old=get(id);List<PlannedRecipe> values=new ArrayList<>(old.recipes());values.add(new PlannedRecipe(null,recipes.get(recipeId),requirePortions(portions),values.size()+1,PlannedRecipeStatus.PLANNED));return save(old,old.name(),values);}
 @Transactional public MealPlan updateRecipe(UUID id,UUID plannedId,int portions,Integer sortOrder){MealPlan old=get(id);PlannedRecipe target=owned(old,plannedId);if(target.status()==PlannedRecipeStatus.COOKED)throw new ConflictException("Cooked planned recipes are final");List<PlannedRecipe> values=old.recipes().stream().map(r->r.id().equals(plannedId)?new PlannedRecipe(r.id(),r.recipe(),r.recipeName(),requirePortions(portions),sortOrder==null?r.sortOrder():sortOrder,r.status()):r).sorted(Comparator.comparingInt(PlannedRecipe::sortOrder)).toList();validateOrders(values);return save(old,old.name(),values);}
 @Transactional public RecipeCookResult cook(UUID id,UUID plannedId){MealPlan old=get(id);PlannedRecipe target=owned(old,plannedId);if(target.status()!=PlannedRecipeStatus.PLANNED)throw new ConflictException("Only planned recipes can be cooked");RecipeCookResult result=interactions.cook(target.recipe().id(),BigDecimal.valueOf(target.portions()),id);List<PlannedRecipe> values=old.recipes().stream().map(r->r.id().equals(plannedId)?new PlannedRecipe(r.id(),r.recipe(),r.recipeName(),r.portions(),r.sortOrder(),PlannedRecipeStatus.COOKED):r).toList();save(old,old.name(),values);return result;}
 @Transactional public MealPlan skip(UUID id,UUID plannedId){MealPlan old=get(id);PlannedRecipe target=owned(old,plannedId);if(target.status()==PlannedRecipeStatus.COOKED)throw new ConflictException("Cooked planned recipes are final");if(target.status()==PlannedRecipeStatus.SKIPPED&&target.recipe()==null)throw new ConflictException("Den slettede opskrift kan ikke føjes tilbage til madplanen");PlannedRecipeStatus next=target.status()==PlannedRecipeStatus.SKIPPED?PlannedRecipeStatus.PLANNED:PlannedRecipeStatus.SKIPPED;List<PlannedRecipe> values=old.recipes().stream().map(r->r.id().equals(plannedId)?new PlannedRecipe(r.id(),r.recipe(),r.recipeName(),r.portions(),r.sortOrder(),next):r).toList();return save(old,old.name(),values);}
 @Transactional public MealPlan removeRecipe(UUID id,UUID plannedId){MealPlan old=get(id);owned(old,plannedId);List<PlannedRecipe> values=new ArrayList<>();for(PlannedRecipe r:old.recipes())if(!r.id().equals(plannedId))values.add(new PlannedRecipe(r.id(),r.recipe(),r.recipeName(),r.portions(),values.size()+1,r.status()));return save(old,old.name(),values);}
 public RecipeRequirementCalculation requirements(UUID id){List<RecipeSelection>s=selections(get(id));return s.isEmpty()?new RecipeRequirementCalculation(List.of()):interactions.calculate(s,id);} @Transactional public RecipeRequirementCalculation addMissing(UUID id){List<RecipeSelection>s=selections(get(id));return s.isEmpty()?new RecipeRequirementCalculation(List.of()):interactions.addMissingToShoppingList(s,id);} @Transactional public void delete(UUID id){get(id);port.deleteByIdAndUserId(id,currentUser.currentUserId());}
 private List<RecipeSelection> selections(MealPlan plan){return plan.recipes().stream().filter(r->r.status()==PlannedRecipeStatus.PLANNED).map(r->new RecipeSelection(r.recipe().id(),BigDecimal.valueOf(r.portions()))).toList();} private MealPlan save(MealPlan old,String name,List<PlannedRecipe> values){return port.save(new MealPlan(old.id(),old.userId(),name,old.createdAt(),Instant.now(),List.copyOf(values)));} private PlannedRecipe owned(MealPlan plan,UUID id){return plan.recipes().stream().filter(r->r.id().equals(id)).findFirst().orElseThrow(()->new ResourceNotFoundException("Planned recipe",id));} private void validateName(String name){if(name==null||name.isBlank())throw new InvalidInputException("Meal plan name is required");} private int wholePortions(BigDecimal p){if(p==null||p.signum()<=0||p.stripTrailingZeros().scale()>0)throw new InvalidInputException("Portions must be a positive whole number");return p.intValueExact();} private int requirePortions(int p){if(p<=0)throw new InvalidInputException("Portions must be positive");return p;} private void validateOrders(List<PlannedRecipe> r){if(r.stream().map(PlannedRecipe::sortOrder).distinct().count()!=r.size()||r.stream().anyMatch(x->x.sortOrder()<=0))throw new InvalidInputException("Sort order must be positive and unique");}
}
