package dk.jamesbabz.madkursus.service.applications;
import java.math.BigDecimal; import java.time.Instant; import java.util.*; import dk.jamesbabz.madkursus.service.exceptions.*; import dk.jamesbabz.madkursus.service.models.*; import dk.jamesbabz.madkursus.service.ports.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor public class RecipeService {
 private final RecipePort port; private final ProductTemplateService templates; private final CurrentUserProvider currentUser;
 public record IngredientInput(UUID templateId,BigDecimal quantity,RecipeUnit unit,String preparation,int sortOrder){} public record StepInput(String instruction,int sortOrder){}
 public List<Recipe> getAll(){return port.findAllByUserId(currentUser.currentUserId());} public Recipe get(UUID id){return port.findByIdAndUserId(id,currentUser.currentUserId()).orElseThrow(()->new ResourceNotFoundException("Recipe",id));}
 @Transactional public Recipe create(String name,String description,List<IngredientInput> ingredients,List<StepInput> steps){return persist(null,null,name,description,ingredients,steps,null);}
 @Transactional public Recipe createFromTemplate(RecipeTemplate template){Instant now=Instant.now();return port.save(new Recipe(null,currentUser.currentUserId(),template.id(),template.name(),template.description(),now,now,template.ingredients().stream().map(i->new RecipeIngredient(null,i.productTemplate(),i.quantity(),i.unit(),i.preparation(),i.sortOrder())).toList(),template.steps().stream().map(s->new RecipeStep(null,s.instruction(),s.sortOrder())).toList()));}
 @Transactional public Recipe update(UUID id,String name,String description,List<IngredientInput> ingredients,List<StepInput> steps){Recipe old=get(id);return persist(id,old.sourceTemplateId(),name,description,ingredients,steps,old.createdAt());}
 @Transactional public void delete(UUID id){get(id);port.deleteByIdAndUserId(id,currentUser.currentUserId());}
 private Recipe persist(UUID id,UUID sourceTemplateId,String name,String description,List<IngredientInput> inputs,List<StepInput> stepInputs,Instant created){if(name==null||name.isBlank())throw new InvalidInputException("Recipe name is required");validateOrders(inputs.stream().map(IngredientInput::sortOrder).toList());validateOrders(stepInputs.stream().map(StepInput::sortOrder).toList());List<RecipeIngredient> ingredients=inputs.stream().map(i->{if(i.templateId()==null||i.quantity()==null||i.quantity().signum()<=0||i.unit()==null)throw new InvalidInputException("Ingredient template, quantity and unit are required");return new RecipeIngredient(null,templates.get(i.templateId()),i.quantity(),i.unit(),blankToNull(i.preparation()),i.sortOrder());}).sorted(Comparator.comparingInt(RecipeIngredient::sortOrder)).toList();List<RecipeStep> steps=stepInputs.stream().map(s->{if(s.instruction()==null||s.instruction().isBlank())throw new InvalidInputException("Step instruction is required");return new RecipeStep(null,s.instruction().trim(),s.sortOrder());}).sorted(Comparator.comparingInt(RecipeStep::sortOrder)).toList();Instant now=Instant.now();return port.save(new Recipe(id,currentUser.currentUserId(),sourceTemplateId,name.trim(),blankToNull(description),created==null?now:created,now,ingredients,steps));}
 private void validateOrders(List<Integer> values){if(values.stream().anyMatch(v->v==null||v<=0)||new HashSet<>(values).size()!=values.size())throw new InvalidInputException("Sort order must be positive and unique");}private String blankToNull(String v){return v==null||v.isBlank()?null:v.trim();}
}
