package dk.jamesbabz.madkursus.service.applications;
import dk.jamesbabz.madkursus.service.exceptions.InvalidInputException;import dk.jamesbabz.madkursus.service.models.*;import org.springframework.stereotype.Component;import java.math.*;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;
@Component public class RecipeInstructionRenderer {
 public String render(RecipeStructuredInstruction instruction,List<? extends Object> ingredientValues,List<PreparedComponent> components,BigDecimal portions){if(instruction==null)return null;Map<UUID,Ingredient> ingredients=ingredientValues.stream().map(this::ingredient).collect(Collectors.toMap(Ingredient::id,Function.identity()));Map<UUID,PreparedComponent> componentMap=components.stream().collect(Collectors.toMap(PreparedComponent::id,Function.identity()));StringBuilder out=new StringBuilder();for(RecipeInstructionPart part:instruction.parts()){int populated=(part.text()!=null?1:0)+(part.recipeIngredientId()!=null?1:0)+(part.preparedComponentId()!=null?1:0)+(part.scaledNumber()!=null?1:0);if(populated!=1)throw new InvalidInputException("Structured instruction part must contain exactly one value");if(part.text()!=null)out.append(part.text());else if(part.preparedComponentId()!=null){PreparedComponent c=componentMap.get(part.preparedComponentId());if(c==null)throw new InvalidInputException("Structured instruction references unknown PreparedComponent");out.append(c.name());}else if(part.scaledNumber()!=null)out.append(decimal(part.scaledNumber().multiply(portions)));else{Ingredient i=ingredients.get(part.recipeIngredientId());if(i==null)throw new InvalidInputException("Structured instruction references unknown ingredient");BigDecimal quantity=(part.quantity()==null?i.quantity():part.quantity()).multiply(portions);RecipeUnit unit=part.unit()==null?i.unit():part.unit();out.append(format(quantity,unit)).append(' ').append(i.name());}}return out.toString();}
 private Ingredient ingredient(Object value){if(value instanceof RecipeIngredient i)return new Ingredient(i.id(),i.productTemplate().name(),i.quantity(),i.unit());if(value instanceof RecipeTemplateIngredient i)return new Ingredient(i.id(),i.productTemplate().name(),i.quantity(),i.unit());throw new IllegalArgumentException("Unsupported ingredient model");}
 private String format(BigDecimal value,RecipeUnit unit){if(unit==RecipeUnit.GRINDER_TURN)value=value.setScale(0,RoundingMode.HALF_UP);return decimal(value)+" "+switch(unit){case GRAM->"g";case MILLILITER->"ml";case DECILITER->"dl";case TEASPOON->"tsk";case TABLESPOON->"spsk";case PIECE->"stk";case GRINDER_TURN->value.compareTo(BigDecimal.ONE)==0?"omgang":"omgange";};}
 private String decimal(BigDecimal value){value=value.stripTrailingZeros();if(value.scale()<=0)return value.toPlainString();BigDecimal whole=value.setScale(0,RoundingMode.DOWN),fraction=value.subtract(whole);String glyph=fraction.compareTo(new BigDecimal("0.25"))==0?"¼":fraction.compareTo(new BigDecimal("0.5"))==0?"½":fraction.compareTo(new BigDecimal("0.75"))==0?"¾":null;if(glyph!=null)return whole.signum()==0?glyph:whole.toPlainString()+glyph;return value.toPlainString().replace('.',',');}
 private record Ingredient(UUID id,String name,BigDecimal quantity,RecipeUnit unit){}
}
